<?php

namespace ContainerMJhHyNv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDataSQLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ptNJgDk.App\Entity\UserDataSQL' shared service.
     *
     * @return \App\Entity\UserDataSQL
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ptNJgDk": it needs an instance of "App\\Entity\\UserDataSQL" but this type has been excluded in "config/services.yaml".');
    }
}
