<?php

namespace ContainerMJhHyNv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWelcomePageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\WelcomePageType' shared autowired service.
     *
     * @return \App\Form\Type\WelcomePageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/WelcomePageType.php';

        return $container->privates['App\\Form\\Type\\WelcomePageType'] = new \App\Form\Type\WelcomePageType();
    }
}
