<?php

namespace ContainerVm8Doxj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\TaskType' shared autowired service.
     *
     * @return \App\Form\Type\TaskType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/TaskType.php';

        return $container->privates['App\\Form\\Type\\TaskType'] = new \App\Form\Type\TaskType();
    }
}
