<?php

namespace ContainerTAXszgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TUEf9IWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TUEf9IW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TUEf9IW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProductController::createProduct' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TaskController::taskByEmail' => ['privates', '.service_locator.m21sx_C', 'get_ServiceLocator_M21sxCService', true],
            'App\\Controller\\UserDataSQLController::delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController::display' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController::login' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController::panelByEmail' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController::showByName' => ['privates', '.service_locator.ptNJgDk', 'get_ServiceLocator_PtNJgDkService', true],
            'App\\Controller\\UserDataSQLController::updateByEmail' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController::welcome' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProductController:createProduct' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TaskController:taskByEmail' => ['privates', '.service_locator.m21sx_C', 'get_ServiceLocator_M21sxCService', true],
            'App\\Controller\\UserDataSQLController:delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController:display' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController:login' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController:panelByEmail' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController:showByName' => ['privates', '.service_locator.ptNJgDk', 'get_ServiceLocator_PtNJgDkService', true],
            'App\\Controller\\UserDataSQLController:updateByEmail' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserDataSQLController:welcome' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProductController::createProduct' => '?',
            'App\\Controller\\TaskController::taskByEmail' => '?',
            'App\\Controller\\UserDataSQLController::delete' => '?',
            'App\\Controller\\UserDataSQLController::display' => '?',
            'App\\Controller\\UserDataSQLController::login' => '?',
            'App\\Controller\\UserDataSQLController::new' => '?',
            'App\\Controller\\UserDataSQLController::panelByEmail' => '?',
            'App\\Controller\\UserDataSQLController::showByName' => '?',
            'App\\Controller\\UserDataSQLController::updateByEmail' => '?',
            'App\\Controller\\UserDataSQLController::welcome' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProductController:createProduct' => '?',
            'App\\Controller\\TaskController:taskByEmail' => '?',
            'App\\Controller\\UserDataSQLController:delete' => '?',
            'App\\Controller\\UserDataSQLController:display' => '?',
            'App\\Controller\\UserDataSQLController:login' => '?',
            'App\\Controller\\UserDataSQLController:new' => '?',
            'App\\Controller\\UserDataSQLController:panelByEmail' => '?',
            'App\\Controller\\UserDataSQLController:showByName' => '?',
            'App\\Controller\\UserDataSQLController:updateByEmail' => '?',
            'App\\Controller\\UserDataSQLController:welcome' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
