<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMJhHyNv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMJhHyNv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMJhHyNv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMJhHyNv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMJhHyNv\App_KernelDevDebugContainer([
    'container.build_hash' => 'MJhHyNv',
    'container.build_id' => '93bc844f',
    'container.build_time' => 1691141289,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMJhHyNv');
