<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVm8Doxj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVm8Doxj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVm8Doxj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVm8Doxj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVm8Doxj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vm8Doxj',
    'container.build_id' => '2ad86156',
    'container.build_time' => 1691415956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVm8Doxj');
