<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXAGOcz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXAGOcz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXAGOcz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXAGOcz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXAGOcz\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXAGOcz',
    'container.build_id' => '31428d24',
    'container.build_time' => 1691419219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXAGOcz');
